/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.Alunos;
import model.dao.AlunosDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author R
 */
public class ViewCadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form ViewCadastroFornecedores
     */
    public ViewCadastroAlunos() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTAlunos.getModel();
        jTAlunos.setRowSorter(new TableRowSorter(modelo));

        listarTabela();

    }

    public void listarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTAlunos.getModel();
        modelo.setNumRows(0);

        AlunosDAO adao = new AlunosDAO();

        for (Alunos a : adao.leitura()) {

            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCpf(),
                a.getRg(),
                a.getSexo(),
                a.getDataMatric(),
                a.getDataNasc(),
                a.getTelefone(),
                a.getCelular(),
                a.getEmail(),
                a.getEndereco(),
                a.getBairro(),
                a.getComplemento(),
                a.getUf(),
                a.getCidade(),
                a.getCep(),});
        }
    }

    public void Pesquisar_AlunoNome(String nome) {
        DefaultTableModel modelo = (DefaultTableModel) jTAlunos.getModel();
        modelo.setNumRows(0);

        AlunosDAO adao = new AlunosDAO();

        for (Alunos a : adao.Pesquisar_Alunos(nome)) {

            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCpf(),
                a.getRg(),
                a.getSexo(),
                a.getDataMatric(),
                a.getDataNasc(),
                a.getTelefone(),
                a.getCelular(),
                a.getEmail(),
                a.getEndereco(),
                a.getBairro(),
                a.getComplemento(),
                a.getUf(),
                a.getCidade(),
                a.getCep(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdAluno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtComp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        JcbUF = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlunos = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        labelData = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNasc = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JcbSexo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtRg = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        txtBuscarAluno = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("ID");

        txtIdAluno.setEditable(false);
        txtIdAluno.setBackground(new java.awt.Color(204, 204, 255));
        txtIdAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setText("*CPF");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("*Nome");

        jLabel10.setText("*Telefone");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Celular");

        jLabel14.setText("*E-mail");

        jLabel4.setText("Endereço");

        jLabel6.setText("Bairro");

        jLabel5.setText("Cidade");

        jLabel8.setText("Complemento");

        jLabel9.setText("*CEP");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("UF");

        JcbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "ES", "RJ", "CE", "MG", "GO", "DF", "RS", "RN", "MT", "PR", "SC", "BA", "AM", "AC", "TO", "AP", "AL", "MA", "PA", "RO", "RR", "SE", "MS", "PE", "PB", "PI" }));

        jButtonSalvar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(0, 51, 204));
        jButtonSalvar.setText("Novo");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "Sexo", "Data Matricula", "Data Nasc", "Telefone", "Celular", "Email", "Endereco", "Bairro", "Complemento", "UF", "Cidade", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAlunosMouseClicked(evt);
            }
        });
        jTAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTAlunosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTAlunos);

        jButtonAlterar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(0, 153, 51));
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setBackground(new java.awt.Color(255, 204, 204));
        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(204, 0, 0));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(102, 0, 153));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        labelData.setForeground(new java.awt.Color(0, 102, 0));
        labelData.setText("Data");

        jLabel11.setText("( * ) Campos Obrigatórios ");

        try {
            txtMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        jLabel13.setText("Data Matricula");

        try {
            txtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascActionPerformed(evt);
            }
        });

        jLabel15.setText("Data Nascimento");

        jLabel16.setText("sexo");

        JcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel17.setText("RG");

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 0)));
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));

        txtBuscarAluno.setToolTipText("Informe o nome do Aluno");
        txtBuscarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButtonPesquisar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(0, 153, 51));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisar)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jButtonSalvar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAlterar)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonExcluir)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonLimpar)
                                .addGap(40, 40, 40)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBai, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(189, 189, 189))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(257, 257, 257))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelData)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel11)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(158, 158, 158))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(labelData))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonAlterar)
                            .addComponent(jButtonExcluir)
                            .addComponent(jButtonLimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1210, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // Inserindo fornecedores

        Alunos a = new Alunos();
        AlunosDAO dao = new AlunosDAO();

        // Campos Obrigatórios:
        if ((txtCpf.getText().equals("")) || (txtNome.getText().equals("")) || (txtTelefone.getText().equals("")) || (txtEmail.getText().equals("")) || (txtCEP.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
        a.setNome(txtNome.getText());
        a.setCpf(txtCpf.getText());
        a.setRg(txtRg.getText());
        a.setSexo(JcbSexo.getSelectedItem().toString());
        a.setDataMatric(txtMatricula.getText());
        a.setDataNasc(txtNasc.getText());
        a.setTelefone(txtTelefone.getText());
        a.setCelular(txtCelular.getText());
        a.setEmail(txtEmail.getText());
        a.setEndereco(txtEnd.getText());
        a.setBairro(txtBai.getText());
        a.setComplemento(txtComp.getText());
        a.setUf(JcbUF.getSelectedItem().toString());
        a.setCidade(txtCid.getText());
        a.setCep(txtCEP.getText());

        dao.Inserir(a);
        listarTabela();

        // Apagar o que foi digitado depois que confirmado o cadastro
        txtNome.setText(null);
        txtCpf.setText(null);
        txtRg.setText(null);
        txtMatricula.setText(null);
        txtNasc.setText(null);
        txtTelefone.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        txtEnd.setText(null);
        txtBai.setText(null);
        txtComp.setText(null);
        txtCid.setText(null);
        txtCEP.setText(null);


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // método para alterar fornecedores
        if (jTAlunos.getSelectedRow() != -1) {

            Alunos a = new Alunos();
            AlunosDAO dao = new AlunosDAO();

            if ((txtCpf.getText().equals("")) || (txtNome.getText().equals("")) || (txtTelefone.getText().equals("")) || (txtEmail.getText().equals("")) || (txtCEP.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            a.setId((int) jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0));
            a.setNome(txtNome.getText());
            a.setCpf(txtCpf.getText());
            a.setRg(txtRg.getText());
            a.setSexo(JcbSexo.getSelectedItem().toString());
            a.setDataMatric(txtMatricula.getText());
            a.setDataNasc(txtNasc.getText());
            a.setTelefone(txtTelefone.getText());
            a.setCelular(txtCelular.getText());
            a.setEmail(txtEmail.getText());
            a.setEndereco(txtEnd.getText());
            a.setBairro(txtBai.getText());
            a.setComplemento(txtComp.getText());
            a.setUf(JcbUF.getSelectedItem().toString());
            a.setCidade(txtCid.getText());
            a.setCep(txtCEP.getText());
            dao.alterar(a);
            listarTabela();

            // Apagar o que foi digitado depois que confirmado o cadastro
            txtIdAluno.setText(null);
            txtNome.setText(null);
            txtCpf.setText(null);
            txtRg.setText(null);
            txtMatricula.setText(null);
            txtNasc.setText(null);
            txtTelefone.setText(null);
            txtCelular.setText(null);
            txtEmail.setText(null);
            txtEnd.setText(null);
            txtBai.setText(null);
            txtComp.setText(null);
            txtCid.setText(null);
            txtCEP.setText(null);
            jButtonSalvar.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAlunosKeyReleased
        // setar campos dos dados cadastrados da tabela para os campos de preenchimento

        if (jTAlunos.getSelectedRow() != -1) {

            txtIdAluno.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0).toString());
            txtNome.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 1).toString());
            txtCpf.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 2).toString());
            txtRg.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 3).toString());
            JcbSexo.setSelectedItem(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 4).toString());
            txtMatricula.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 5).toString());
            txtNasc.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 6).toString());
            txtTelefone.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 7).toString());
            txtCelular.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 8).toString());
            txtEmail.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 9).toString());
            txtEnd.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 10).toString());
            txtBai.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 11).toString());
            txtComp.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 12).toString());
            JcbUF.setSelectedItem(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 13).toString());
            txtCid.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 14).toString());
            txtCEP.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 15).toString());

        }
    }//GEN-LAST:event_jTAlunosKeyReleased

    private void jTAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAlunosMouseClicked
        // setar campos da tabela

        if (jTAlunos.getSelectedRow() != -1) {

            txtIdAluno.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0).toString());
            txtNome.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 1).toString());
            txtCpf.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 2).toString());
            txtRg.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 3).toString());
            JcbSexo.setSelectedItem(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 4).toString());
            txtMatricula.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 5).toString());
            txtNasc.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 6).toString());
            txtTelefone.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 7).toString());
            txtCelular.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 8).toString());
            txtEmail.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 9).toString());
            txtEnd.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 10).toString());
            txtBai.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 11).toString());
            txtComp.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 12).toString());
            JcbUF.setSelectedItem(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 13).toString());
            txtCid.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 14).toString());
            txtCEP.setText(jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 15).toString());

            jButtonSalvar.setEnabled(false);

        }

    }//GEN-LAST:event_jTAlunosMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // o método faz exclusão dos dados cadastrados
        if (jTAlunos.getSelectedRow() != -1) {

            Alunos a = new Alunos();
            AlunosDAO dao = new AlunosDAO();

            a.setId((int) jTAlunos.getValueAt(jTAlunos.getSelectedRow(), 0));
            dao.excluir(a);
            listarTabela();

            // Apagar o que foi digitado depois que confirmado o cadastro
            txtIdAluno.setText(null);
            txtNome.setText(null);
            txtCpf.setText(null);
            txtRg.setText(null);
            txtMatricula.setText(null);
            txtNasc.setText(null);
            txtTelefone.setText(null);
            txtCelular.setText(null);
            txtEmail.setText(null);
            txtEnd.setText(null);
            txtBai.setText(null);
            txtComp.setText(null);
            txtCid.setText(null);
            txtCEP.setText(null);

            jButtonSalvar.setEnabled(false);

        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // o método pesquisa pelo a razao do fornecedor
        Pesquisar_AlunoNome(txtBuscarAluno.getText());


    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // método para limpar os campos digitados

        Alunos a = new Alunos();
        AlunosDAO dao = new AlunosDAO();

        txtIdAluno.setText(null);
        txtNome.setText(null);
        txtCpf.setText(null);
        txtRg.setText(null);
        txtMatricula.setText(null);
        txtNasc.setText(null);
        txtTelefone.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        txtEnd.setText(null);
        txtBai.setText(null);
        txtComp.setText(null);
        txtCid.setText(null);
        txtCEP.setText(null);

        jButtonSalvar.setEnabled(true);


    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // formatando e atualizando a data no Jframe
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        labelData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void txtNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroAlunos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbSexo;
    private javax.swing.JComboBox<String> JcbUF;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAlunos;
    private javax.swing.JLabel labelData;
    private javax.swing.JTextField txtBai;
    private javax.swing.JTextField txtBuscarAluno;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtComp;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtIdAluno;
    private javax.swing.JFormattedTextField txtMatricula;
    private javax.swing.JFormattedTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

}
